name: "Build"

on:
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8' # The JDK version to make available on the path.

    #- name: Build with Gradle
    #  run: gradle build
    - name: Build with Gradle
      run: ./gradlew build
